Database Implementation Techniques Programming Task SoSe2016: CoGaDB::ColumnBaseTyped< T > Class Template Reference
CoGaDB::ColumnBaseTyped< T > Class Template Reference abstract
This class represents a column with type T, is the base class for all typed column classes and allows a uniform handling of columns of a certain type T.
#include <column_base_typed.hpp>
Public Member Functions
ColumnBaseTyped (const std::string &name, AttributeType db_type)
virtual ~ColumnBaseTyped ()
virtual bool insert (const boost::any &new_Value)=0
appends a value new_Value to end of column
virtual bool insert (const T &new_Value)=0
virtual bool update (TID tid, const boost::any &new_value)=0
updates the value on position tid with a value new_Value
virtual bool update (PositionListPtr tid, const boost::any &new_value)=0
updates the values specified by the position list with a value new_Value
virtual bool remove (TID tid)=0
deletes the value on position tid
virtual bool remove (PositionListPtr tid)=0
deletes the values defined in the position list
virtual bool clearContent ()=0
deletes all values stored in the column
virtual const boost::any get (TID tid)=0
generic function for fetching a value form a column (slow)
virtual void print () const =0 throw ()
prints the content of a column
virtual size_t size () const =0 throw ()
returns the number of values (rows) in a column
virtual unsigned int getSizeinBytes () const =0 throw ()
returns the size in bytes the column consumes in main memory
virtual const ColumnPtr copy () const =0
virtual copy constructor
virtual const PositionListPtr sort (SortOrder order)
sorts a column w.r.t. a SortOrder
virtual const PositionListPtr selection (const boost::any &value_for_comparison, const ValueComparator comp)
filters the values of a column according to a filter condition consisting of a comparison value and a ValueComparator (=,<,>)
virtual const PositionListPtr parallel_selection (const boost::any &value_for_comparison, const ValueComparator comp, unsigned int number_of_threads)
filters the values of a column in parallel according to a filter condition consisting of a comparison value and a ValueComparator (=,<,>)
virtual const PositionListPairPtr hash_join (ColumnPtr join_column)
joins two columns using the hash join algorithm
virtual const PositionListPairPtr sort_merge_join (ColumnPtr join_column)
joins two columns using the sort merge join algorithm
virtual const PositionListPairPtr nested_loop_join (ColumnPtr join_column)
joins two columns using the nested loop join algorithm
virtual bool add (const boost::any &new_Value)
adds constant to column
virtual bool add (ColumnPtr join_column)
vector addition of two columns
virtual bool minus (const boost::any &new_Value)
substracts constant from column
virtual bool minus (ColumnPtr join_column)
vector substraction of two columns
virtual bool multiply (const boost::any &new_Value)
multiply constant with column
virtual bool multiply (ColumnPtr join_column)
multiply two columns A and B
virtual bool division (const boost::any &new_Value)
devide values in column by a constant
virtual bool division (ColumnPtr join_column)
devide column A with column B
virtual bool store (const std::string &path)=0
store a column on the disc
virtual bool load (const std::string &path)=0
load column from disc
virtual bool isMaterialized () const =0 throw ()
use this method to determine whether the column is materialized or a Lookup Column
virtual bool isCompressed () const =0 throw ()
use this method to determine whether the column is materialized or a Lookup Column
virtual const std::type_info & type () const throw ()
returns type information of internal values
virtual T & operator[] (const int index)=0
defines operator[] for this class, which enables the user to thread all typed columns as arrays.
bool operator== (ColumnBaseTyped< T > &column)
template<>
bool add (const boost::any &)
adds constant to column
template<>
bool add (ColumnPtr)
vector addition of two columns
template<>
bool minus (const boost::any &)
substracts constant from column
template<>
bool minus (ColumnPtr)
vector substraction of two columns
template<>
bool multiply (const boost::any &)
multiply constant with column
template<>
bool multiply (ColumnPtr)
multiply two columns A and B
template<>
bool division (const boost::any &)
devide values in column by a constant
template<>
bool division (ColumnPtr)
devide column A with column B
Public Member Functions inherited from CoGaDB::ColumnBase
ColumnBase (const std::string &name, AttributeType db_type)
virtual ~ColumnBase ()
AttributeType getType () const throw ()
returns database type of column (as defined in "SQL" statement)
const std::string getName () const throw ()
returns attribute name of column
Additional Inherited Members
Public Types inherited from CoGaDB::ColumnBase
typedef shared_pointer_namespace::shared_ptr< ColumnBase > ColumnPtr
defines a smart pointer to a ColumnBase Object
Protected Attributes inherited from CoGaDB::ColumnBase
std::string name_
attribute name of the column
AttributeType db_type_
database type of the column
Detailed Description
template<class T>
class CoGaDB::ColumnBaseTyped< T >
This class represents a column with type T, is the base class for all typed column classes and allows a uniform handling of columns of a certain type T.
This class is indentended to be a base class, so it has a virtual destruktor and pure virtual methods, which need to be implemented in a derived class. Furthermore, it declares pure virtual methods to allow a generic handling of typed columns, e.g., operator[]. All algorithms can be applied to a typed column, because of this operator. This abstracts from a columns implementation detail, e.g., whether they are compressed or not.
Author
Sebastian Breß
Version
0.2
Date
2013
Copyright
GNU LESSER GENERAL PUBLIC LICENSE - Version 3, http://www.gnu.org/licenses/lgpl-3.0.txt
Definition at line 33 of file column_base_typed.hpp.
Constructor & Destructor Documentation
template<class T > CoGaDB::ColumnBaseTyped< T >::ColumnBaseTyped (const std::string & name, AttributeType db_type)
Definition at line 99 of file column_base_typed.hpp.
template<class T > CoGaDB::ColumnBaseTyped< T >::~ColumnBaseTyped () virtual
Definition at line 104 of file column_base_typed.hpp.
Member Function Documentation
template<class Type > bool CoGaDB::ColumnBaseTyped< Type >::add (const boost::any & new_Value) virtual
adds constant to column
for all indeces i holds the following property: B[i]=A[i]+new_Value
Implements CoGaDB::ColumnBase.
Definition at line 298 of file column_base_typed.hpp.
References CoGaDB::ColumnBaseTyped< T >::operator[](), and CoGaDB::ColumnBaseTyped< T >::size().
template<class Type > bool CoGaDB::ColumnBaseTyped< Type >::add (ColumnPtr column) virtual
vector addition of two columns
for all indeces i holds the following property: C[i]=A[i]+B[i]
Implements CoGaDB::ColumnBase.
Definition at line 315 of file column_base_typed.hpp.
References CoGaDB::ColumnBaseTyped< T >::operator[](), and CoGaDB::ColumnBaseTyped< T >::size().
template<> bool CoGaDB::ColumnBaseTyped< std::string >::add (const boost::any & new_Value) inline virtual
adds constant to column
for all indeces i holds the following property: B[i]=A[i]+new_Value
Implements CoGaDB::ColumnBase.
Definition at line 407 of file column_base_typed.hpp.
template<> bool CoGaDB::ColumnBaseTyped< std::string >::add (ColumnPtr column) inline virtual
vector addition of two columns
for all indeces i holds the following property: C[i]=A[i]+B[i]
Implements CoGaDB::ColumnBase.
Definition at line 409 of file column_base_typed.hpp.
template<class T> virtual bool CoGaDB::ColumnBaseTyped< T >::clearContent () pure virtual
deletes all values stored in the column
Returns
true for sucess and false in case an error occured
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::DictionaryCompressedColumn< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
template<class T> virtual const ColumnPtr CoGaDB::ColumnBaseTyped< T >::copy () const pure virtual
virtual copy constructor
Returns
a ColumnPtr to an exakt copy of the current column
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::DictionaryCompressedColumn< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
template<class Type > bool CoGaDB::ColumnBaseTyped< Type >::division (const boost::any & new_Value) virtual
devide values in column by a constant
for all indeces i holds the following property: B[i]=A[i]/new_Value
Implements CoGaDB::ColumnBase.
Definition at line 380 of file column_base_typed.hpp.
References CoGaDB::ColumnBaseTyped< T >::operator[](), and CoGaDB::ColumnBaseTyped< T >::size().
template<class Type > bool CoGaDB::ColumnBaseTyped< Type >::division (ColumnPtr column) virtual
devide column A with column B
for all indeces i holds the following property: C[i]=A[i]/B[i]
Implements CoGaDB::ColumnBase.
Definition at line 395 of file column_base_typed.hpp.
References CoGaDB::ColumnBaseTyped< T >::operator[](), and CoGaDB::ColumnBaseTyped< T >::size().
template<> bool CoGaDB::ColumnBaseTyped< std::string >::division (const boost::any & new_Value) inline virtual
devide values in column by a constant
for all indeces i holds the following property: B[i]=A[i]/new_Value
Implements CoGaDB::ColumnBase.
Definition at line 423 of file column_base_typed.hpp.
template<> bool CoGaDB::ColumnBaseTyped< std::string >::division (ColumnPtr column) inline virtual
devide column A with column B
for all indeces i holds the following property: C[i]=A[i]/B[i]
Implements CoGaDB::ColumnBase.
Definition at line 425 of file column_base_typed.hpp.
template<class T> virtual const boost::any CoGaDB::ColumnBaseTyped< T >::get (TID tid) pure virtual
generic function for fetching a value form a column (slow)
check whether the object is valid (e.g., when a tid is not valid, then the returned object is invalid as well)
Returns
object of type boost::any containing the value on position tid
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::DictionaryCompressedColumn< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
template<class T> virtual unsigned int CoGaDB::ColumnBaseTyped< T >::getSizeinBytes () const throw () pure virtual
returns the size in bytes the column consumes in main memory
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::Column< T >, CoGaDB::LookupArray< T >, CoGaDB::DictionaryCompressedColumn< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
template<class T > const PositionListPairPtr CoGaDB::ColumnBaseTyped< T >::hash_join (ColumnPtr join_column) virtual
joins two columns using the hash join algorithm
Returns
PositionListPairPtr to a PositionListPair, which represents the result
Implements CoGaDB::ColumnBase.
Definition at line 200 of file column_base_typed.hpp.
References CoGaDB::ColumnBase::name_, and CoGaDB::ColumnBaseTyped< T >::size().
template<class T> virtual bool CoGaDB::ColumnBaseTyped< T >::insert (const boost::any & new_Value) pure virtual
appends a value new_Value to end of column
Returns
true for sucess and false in case an error occured
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::CompressedColumn< T >, CoGaDB::DictionaryCompressedColumn< T >, and CoGaDB::Column< T >.
template<class T> virtual bool CoGaDB::ColumnBaseTyped< T >::insert (const T & new_Value) pure virtual
Implemented in CoGaDB::LookupArray< T >, CoGaDB::CompressedColumn< T >, CoGaDB::DictionaryCompressedColumn< T >, and CoGaDB::Column< T >.
template<class T> virtual bool CoGaDB::ColumnBaseTyped< T >::isCompressed () const throw () pure virtual
use this method to determine whether the column is materialized or a Lookup Column
Returns
true in case the column is storing the compressed values and false otherwise.
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
template<class T> virtual bool CoGaDB::ColumnBaseTyped< T >::isMaterialized () const throw () pure virtual
use this method to determine whether the column is materialized or a Lookup Column
Returns
true in case the column is storing the plain values (without compression) and false in case the column is a LookupColumn.
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
template<class T> virtual bool CoGaDB::ColumnBaseTyped< T >::load (const std::string & path) pure virtual
load column from disc
calling load on a column that is not empty yields undefined behaviour
Returns
true for sucess and false in case an error occured
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::DictionaryCompressedColumn< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
template<class Type > bool CoGaDB::ColumnBaseTyped< Type >::minus (const boost::any & new_Value) virtual
substracts constant from column
for all indeces i holds the following property: B[i]=A[i]-new_Value
Implements CoGaDB::ColumnBase.
Definition at line 328 of file column_base_typed.hpp.
References CoGaDB::ColumnBaseTyped< T >::operator[](), and CoGaDB::ColumnBaseTyped< T >::size().
template<class Type > bool CoGaDB::ColumnBaseTyped< Type >::minus (ColumnPtr column) virtual
vector substraction of two columns
for all indeces i holds the following property: C[i]=A[i]-B[i]
Implements CoGaDB::ColumnBase.
Definition at line 342 of file column_base_typed.hpp.
References CoGaDB::ColumnBaseTyped< T >::operator[](), and CoGaDB::ColumnBaseTyped< T >::size().
template<> bool CoGaDB::ColumnBaseTyped< std::string >::minus (const boost::any & new_Value) inline virtual
substracts constant from column
for all indeces i holds the following property: B[i]=A[i]-new_Value
Implements CoGaDB::ColumnBase.
Definition at line 412 of file column_base_typed.hpp.
template<> bool CoGaDB::ColumnBaseTyped< std::string >::minus (ColumnPtr column) inline virtual
vector substraction of two columns
for all indeces i holds the following property: C[i]=A[i]-B[i]
Implements CoGaDB::ColumnBase.
Definition at line 414 of file column_base_typed.hpp.
template<class Type > bool CoGaDB::ColumnBaseTyped< Type >::multiply (const boost::any & new_Value) virtual
multiply constant with column
for all indeces i holds the following property: B[i]=A[i]*new_Value
Implements CoGaDB::ColumnBase.
Definition at line 354 of file column_base_typed.hpp.
References CoGaDB::ColumnBaseTyped< T >::operator[](), and CoGaDB::ColumnBaseTyped< T >::size().
template<class Type > bool CoGaDB::ColumnBaseTyped< Type >::multiply (ColumnPtr column) virtual
multiply two columns A and B
for all indeces i holds the following property: C[i]=A[i]*B[i]
Implements CoGaDB::ColumnBase.
Definition at line 367 of file column_base_typed.hpp.
References CoGaDB::ColumnBaseTyped< T >::operator[](), and CoGaDB::ColumnBaseTyped< T >::size().
template<> bool CoGaDB::ColumnBaseTyped< std::string >::multiply (const boost::any & new_Value) inline virtual
multiply constant with column
for all indeces i holds the following property: B[i]=A[i]*new_Value
Implements CoGaDB::ColumnBase.
Definition at line 418 of file column_base_typed.hpp.
template<> bool CoGaDB::ColumnBaseTyped< std::string >::multiply (ColumnPtr column) inline virtual
multiply two columns A and B
for all indeces i holds the following property: C[i]=A[i]*B[i]
Implements CoGaDB::ColumnBase.
Definition at line 420 of file column_base_typed.hpp.
template<class Type > const PositionListPairPtr CoGaDB::ColumnBaseTyped< Type >::nested_loop_join (ColumnPtr join_column) virtual
joins two columns using the nested loop join algorithm
Returns
PositionListPairPtr to a PositionListPair, which represents the result
Implements CoGaDB::ColumnBase.
Definition at line 259 of file column_base_typed.hpp.
References CoGaDB::debug, CoGaDB::ColumnBase::name_, and CoGaDB::ColumnBaseTyped< T >::size().
template<class T > bool CoGaDB::ColumnBaseTyped< T >::operator== (ColumnBaseTyped< T > & column) inline
Definition at line 287 of file column_base_typed.hpp.
References CoGaDB::ColumnBaseTyped< T >::size().
template<class T> virtual T& CoGaDB::ColumnBaseTyped< T >::operator[] (const int index) pure virtual
defines operator[] for this class, which enables the user to thread all typed columns as arrays.
Note that this method is pure virtual, so it has to be defined in a derived class.
Returns
a reference to the value at position index
Implemented in CoGaDB::LookupArray< T >, CoGaDB::CompressedColumn< T >, CoGaDB::DictionaryCompressedColumn< T >, and CoGaDB::Column< T >.
Referenced by CoGaDB::ColumnBaseTyped< T >::add(), CoGaDB::ColumnBaseTyped< T >::division(), CoGaDB::ColumnBaseTyped< T >::minus(), and CoGaDB::ColumnBaseTyped< T >::multiply().
template<class T > const PositionListPtr CoGaDB::ColumnBaseTyped< T >::parallel_selection (const boost::any & value_for_comparison, const ValueComparator comp, unsigned int number_of_threads) virtual
filters the values of a column in parallel according to a filter condition consisting of a comparison value and a ValueComparator (=,<,>)
the additional parameter specifies the number of threads that may be used to perform the operation
Returns
PositionListPtr to a PositionList, which represents the result
Implements CoGaDB::ColumnBase.
Definition at line 144 of file column_base_typed.hpp.
template<class T> virtual void CoGaDB::ColumnBaseTyped< T >::print () const throw () pure virtual
prints the content of a column
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::DictionaryCompressedColumn< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
template<class T> virtual bool CoGaDB::ColumnBaseTyped< T >::remove (TID tid) pure virtual
deletes the value on position tid
Returns
true for sucess and false in case an error occured
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::DictionaryCompressedColumn< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
template<class T> virtual bool CoGaDB::ColumnBaseTyped< T >::remove (PositionListPtr tid) pure virtual
deletes the values defined in the position list
assumes tid list is sorted ascending
Returns
true for sucess and false in case an error occured
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::DictionaryCompressedColumn< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
template<class T > const PositionListPtr CoGaDB::ColumnBaseTyped< T >::selection (const boost::any & value_for_comparison, const ValueComparator comp) virtual
filters the values of a column according to a filter condition consisting of a comparison value and a ValueComparator (=,<,>)
Returns
PositionListPtr to a PositionList, which represents the result
Implements CoGaDB::ColumnBase.
Definition at line 154 of file column_base_typed.hpp.
References CoGaDB::EQUAL, CoGaDB::GREATER, CoGaDB::LESSER, CoGaDB::ColumnBase::name_, CoGaDB::quiet, and CoGaDB::ColumnBaseTyped< T >::size().
template<class T> virtual size_t CoGaDB::ColumnBaseTyped< T >::size () const throw () pure virtual
returns the number of values (rows) in a column
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::DictionaryCompressedColumn< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
Referenced by CoGaDB::ColumnBaseTyped< T >::add(), CoGaDB::ColumnBaseTyped< T >::division(), CoGaDB::ColumnBaseTyped< T >::hash_join(), CoGaDB::ColumnBaseTyped< T >::minus(), CoGaDB::ColumnBaseTyped< T >::multiply(), CoGaDB::ColumnBaseTyped< T >::nested_loop_join(), CoGaDB::ColumnBaseTyped< T >::operator==(), CoGaDB::ColumnBaseTyped< T >::selection(), and CoGaDB::ColumnBaseTyped< T >::sort().
template<class T > const PositionListPtr CoGaDB::ColumnBaseTyped< T >::sort (SortOrder order) virtual
sorts a column w.r.t. a SortOrder
Returns
PositionListPtr to a PositionList, which represents the result
Implements CoGaDB::ColumnBase.
Definition at line 114 of file column_base_typed.hpp.
References CoGaDB::ASCENDING, CoGaDB::DESCENDING, and CoGaDB::ColumnBaseTyped< T >::size().
template<class Type > const PositionListPairPtr CoGaDB::ColumnBaseTyped< Type >::sort_merge_join (ColumnPtr join_column) virtual
joins two columns using the sort merge join algorithm
Returns
PositionListPairPtr to a PositionListPair, which represents the result
Implements CoGaDB::ColumnBase.
Definition at line 240 of file column_base_typed.hpp.
References CoGaDB::ColumnBase::name_.
template<class T> virtual bool CoGaDB::ColumnBaseTyped< T >::store (const std::string & path) pure virtual
store a column on the disc
Returns
true for sucess and false in case an error occured
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::DictionaryCompressedColumn< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
template<class T > const std::type_info & CoGaDB::ColumnBaseTyped< T >::type () const throw () virtual
returns type information of internal values
Implements CoGaDB::ColumnBase.
Definition at line 109 of file column_base_typed.hpp.
template<class T> virtual bool CoGaDB::ColumnBaseTyped< T >::update (TID tid, const boost::any & new_Value) pure virtual
updates the value on position tid with a value new_Value
Returns
true for sucess and false in case an error occured
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::DictionaryCompressedColumn< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
template<class T> virtual bool CoGaDB::ColumnBaseTyped< T >::update (PositionListPtr tids, const boost::any & new_value) pure virtual
updates the values specified by the position list with a value new_Value
Returns
true for sucess and false in case an error occured
Implements CoGaDB::ColumnBase.
Implemented in CoGaDB::LookupArray< T >, CoGaDB::DictionaryCompressedColumn< T >, CoGaDB::CompressedColumn< T >, and CoGaDB::Column< T >.
The documentation for this class was generated from the following file:
column_base_typed.hpp